[project]
name = "finalycc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.3",
    "requests>=2.32.5",
    "web3>=7.14.1",
    "werkzeug>=3.1.6",
]
